# Generated by Django 3.2.3 on 2021-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('access_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_name', models.CharField(max_length=255)),
                ('ins_timestamp', models.DateTimeField(auto_now_add=True)),
                ('upd_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_access_type',
                'ordering': ['ins_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('profile_picture', models.FilePathField(path='/media')),
                ('ins_timestamp', models.DateTimeField(auto_now_add=True)),
                ('upd_timestamp', models.DateTimeField(auto_now=True)),
                ('access_types', models.ManyToManyField(to='usermanagement.AccessType')),
            ],
            options={
                'db_table': 't_user',
                'ordering': ['ins_timestamp'],
            },
        ),
    ]
